### ISSUE TITLE
Pyrit 0.5.0 CUDA. error for CUDA module.

### ISSUE THREAD

**Issue by xflyboy** [JPaulMora/Pyrit#479]
Hello.
I have NVIDIA-Linux-x86_64-340.93.run and cuda_7.5.18_linux.run installed on KALI 2
Linux SSD-PC 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux

root@SSD-PC:~/Downloads# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

Installed Pyrit 0.5.0 from GIT.
Pyrit was able to list all CPU cores, perform benchmark on all cores.
Then enabled use_CUDA = true in ~/.pyrit/config
and installed cpyrit-cuda.
Now not able to use pyrit due to following error:

root@SSD-PC:~/Downloads# pyrit list_cores
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 295, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    CUDA =  cpyrit_cuda.listDevices()
NameError: global name 'cpyrit_cuda' is not defined

**Comment by xflyboy** [comment]
root@SSD-PC:~/Downloads# python -c 'from cpyrit import _cpyrit_cuda'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name _cpyrit_cuda

root@SSD-PC:~/Downloads/Pyrit/modules/cpyrit_cuda# python -c 'from cpyrit import _cpyrit_cuda'
does not give any output

Also this were added in ~/.bashrc
export PATH=/usr/local/cuda/bin:$PATH 
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH 


01:00.0 VGA compatible controller: NVIDIA Corporation G92 [GeForce GTS 250] (rev a2)

**Comment by JPaulMora** [comment]
Please try to run it from the python modules directory, Ive tested this in Kali 1, but haven't had time to try Kali2, let me setup a VM and I'll make sure to update my results or a fix if needed.

**Comment by xflyboy** [comment]
It might be related that Processor G92 is not supported (or that  what happened to me) by CUDA 7.5
At least i couldn't run /usr/local/cuda/samples/1_Utilities/deviceQuery# ./deviceQuery on CUDA7.5, 7.0
But it was a success on 6.5. I couldn't find when it was removed from support from RELEAS NOTE.

Now that i have 6.5 i'm not able to install cpyrit_cuda due to gcc4.9 incompatiblity (#error -- unsupported GNU version! gcc 4.9 and up are not supported!) so if i don't solve that issue, i will try to switch back to 7.5 and test what you mentioned.

Thanks for advice any way.

**Comment by JPaulMora** [comment]
Sorry to hear about your CUDA issues, I have personally had some problems too since my primary dev platform has been OS X and CUDA 7.5 doesn't support the Xcode v7 version of clang. As an alternative, id suggest you use the openCL module since it is newer code and thus provides better performance, specially on newer cards like yours. Please feel free to post any recommendation or important info.

**Comment by xflyboy** [comment]
I made a success by using Ubuntu 14.04:
Linux PC 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Nvidia NVIDIA-Linux-x86_64-340.93.run cuda_6.5.14_linux_64.run and pyrit-0.4.0 with both cpyrit-cuda-0.4.0 and cpyrit-opencl-0.4.0.
Is it possible to remove CUDA support and use OPENCL only?
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

The following cores seem available...
#1:  'CUDA-Device #1 'GeForce GTS 250''
#2:  'OpenCL-Device 'GeForce GTS 250''
#3:  'CPU-Core (SSE2)'
#4:  'CPU-Core (SSE2)'

I might try 0.5.0 later but it seems that NVIDIA G92 (GTS250) were removed in later versions of CUDA, so this Issue might be closed as not valid. An advice in removing CPYRIT_CUDA is welcome.
Best luck with the project.

**Comment by xflyboy** [comment]
Seems that above configuration did not worked for CUDA. Again this issue.

pc@PC:~$ pyrit list_cores
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 295, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    CUDA =  cpyrit_cuda.listDevices()
NameError: global name 'cpyrit_cuda' is not defined


Worked OK with OPENCL.
pc@PC:~$ pyrit list_cores
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

The following cores seem available...
#1:  'CPU-Core (SSE2)'
#2:  'CPU-Core (SSE2)'
#3:  'CPU-Core (SSE2)'
#4:  'CPU-Core (SSE2)'

The following OpenCL GPUs seem aviable...
#1:  'OpenCL-Device 'GeForce GTS 250''
pc@PC:~$ pyrit benchmark
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (8329.7 PMKs/s)... \ 

Computed 8329.67 PMKs/s total.
#1: 'CPU-Core (SSE2)': 543.0 PMKs/s (RTT 2.9)
#2: 'CPU-Core (SSE2)': 544.7 PMKs/s (RTT 2.9)
#3: 'CPU-Core (SSE2)': 567.8 PMKs/s (RTT 3.0)
#4: 'CPU-Core (SSE2)': 539.4 PMKs/s (RTT 3.0)
OpenCL:
#1: 'OpenCL-Device 'GeForce GTS 250'': 6306.8 PMKs/s (RTT 2.7)

So you still might want to patch it. If needed tell me what to test and how. Tx.

**Comment by JPaulMora** [comment]
Thanks a lot for this info, good to know you got it working (with openCL). And yes, I'll be providing a fix for the CUDA module on Kali2. Will be leaving issue open until I fix CUDA in case anyone has/needs info.

**Comment by JPaulMora** [comment]
I didn't realize you asked `Is it possible to remove CUDA support and use OPENCL only?' well the answer is yes, on latest version you can enable/disable either module (even CPUs) in the config at ~/.pyrit

**Comment by xflyboy** [comment]
The question was regarding v0.4.0
Thanks any way.
Any idea when the fix will come out? Regards.

**Comment by JPaulMora** [comment]
Question: How did you get CUDA into your system? Was it via dkms?

**Comment by xflyboy** [comment]
All the versions were instulled via .run file from NVIDIA CUDA toolkit webpage. Regards.

**Comment by JPaulMora** [comment]
Alright, heres an update for you. I couldn't install CUDA from the .run file, as it "worked" but left me with a broken X-server. So I ended up installing the toolkit from the official repos (Using dkms). With this method, the CUDA module gets loaded fine, although my GPU still doesn't get listed. So currently my focus will be:

* Debug this listing bug
* Try other Kali/Debian installations to replicate your original bug.

If you still want to use CUDA, feel free to try the dkms method (I believe there is a blackmoreops tut). I'll keep posting updates here as I progress on this matter.

**Comment by alirezadghn** [comment]
Hello, this is test comment
