### ISSUE TITLE
is there any guide for support for Nvidia-CUDA in pyrit 5.0

### ISSUE THREAD

**Issue by zjhxmjl** [JPaulMora/Pyrit#480]
hi,guys!
i had install pyrit 5.0 from your guide,but how can support for Nvidia-CUDA?thanks million!

**Comment by JPaulMora** [comment]
CUDA support is listed on [The Wiki](https://github.com/JPaulMora/Pyrit/wiki/GPU-Acceleration) Feel free to ask here if you run into any problems.

**Comment by zjhxmjl** [comment]
OK,thanks @JPaulMora
