### ISSUE TITLE
NameError: global name 'cpyrit_cuda' is not defined

### ISSUE THREAD

**Issue by zjhxmjl** [JPaulMora/Pyrit#481]
my install method:
1.download https://github.com/JPaulMora/Pyrit/archive/v0.5.0.zip
2.cd Pyrit-0.5 python setup.py build 
3.sudo python setup.py install
4.cd /Pyrit-0.5.0/modules/cpyrit_cuda python setup.py build 
5.sudo python setup.py install
but i get this error info:
zjhxmjl@ubuntu:~/Pyrit-0.5.0/modules/cpyrit_cuda$ pyrit list_cores
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 441, in __init__
    CUDA =  cpyrit_cuda.listDevices()
NameError: global name 'cpyrit_cuda' is not defined

please give me some advance,thanks!
BTW:how to uninstall pyrit?

**Comment by llazzaro** [comment]
Hi,

check my fork with the fix on the dev branch here: https://github.com/llazzaro/Pyrit

copy the file modules/cpyrit_cuda/build/lib.linux-x86_64-2.7/cpyrit/_cpyrit_cuda.so to you library path.

I need to test if after this fix everything is working

**Comment by JPaulMora** [comment]
@llazzaro Awesome! looking forward to it

**Comment by llazzaro** [comment]
PR ready

**Comment by zjhxmjl** [comment]
@llazzaro thks,but I can not test now until I'll come  feedback!

**Comment by zjhxmjl** [comment]
thanks, i find  use devel branch can slove the problem!

**Comment by JPaulMora** [comment]
This issue has been fixed now, you may want to check out [The releases page](https://github.com/JPaulMora/Pyrit/releases/latest)
