### ISSUE TITLE
Pyrit only recognize a single core? 

### ISSUE THREAD

**Issue by zjhxmjl** [JPaulMora/Pyrit#482]
[zjhxmjl@centos ~]$ pyrit list_cores
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

The following cores seem available...
#1:  'CUDA-Device #1 'GeForce GTX 750 Ti''
#2:  'CPU-Core (SSE2)'
When I run the pyrit that is packaged without GTX 750Ti, it will recognize both cores. Any thoughts?
thanks.

**Comment by JPaulMora** [comment]
This is normal behavior, Pyrit leaves 1 free ore per GPU device to manage it's workload. Think of GPUs as the ultimate war machine: All it's power is useless without a brain.
