### ISSUE TITLE
libpcap: unknown file format

### ISSUE THREAD

**Issue by zjhxmjl** [JPaulMora/Pyrit#484]
[zjhxmjl@localhost Desktop]$ pyrit -r 24-69-68-E2-67-26_handshake.cap analyze
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

Parsing file '24-69-68-E2-67-26_handshake.cap' (1/1)...
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 115, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 163, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 447, in analyze
    parser = self._getParser(capturefile)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 178, in _getParser
    dev = cpyrit.pckttools.PcapDevice(capturefile, True)
  File "/usr/lib/python2.7/site-packages/cpyrit/pckttools.py", line 403, in __init__
    self.open_offline(fname)
  File "/usr/lib/python2.7/site-packages/cpyrit/pckttools.py", line 483, in open_offline
    _cpyrit_cpu.PcapDevice.open_offline(self, fname)
IOError: Failed to open file '24-69-68-E2-67-26_handshake.cap' (libpcap: unknown file format)

[zjhxmjl@localhost Desktop]$ pyrit |head -3
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

[zjhxmjl@localhost Desktop]$ lsb_release -a && uname -r
LSB Version:	:core-4.1-ia32:core-4.1-noarch:cxx-4.1-ia32:cxx-4.1-noarch:desktop-4.1-ia32:desktop-4.1-noarch:languages-4.1-ia32:languages-4.1-noarch:printing-4.1-ia32:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 20 (Heisenbug)
Release:	20
Codename:	Heisenbug
3.19.8-100.fc20.i686+PAE
 thanks!

**Comment by JPaulMora** [comment]
hello! I _think_ you have missing dependencies. Did you install **libpcap-devel**?

**Comment by zjhxmjl** [comment]
yes!
[zjhxmjl@localhost Desktop]$ sudo rpm -qa|grep libpcap-devel
libpcap-devel-1.5.3-3.fc20.i686

**Comment by JPaulMora** [comment]
thanks, will try it out

**Comment by zjhxmjl** [comment]
@JPaulMora thanks,maybe my cap file is wrong!I still have a lot of questions for you！
