### ISSUE TITLE
fatal error: CL/cl.h: No such file or directory

### ISSUE THREAD

**Issue by zjhxmjl** [JPaulMora/Pyrit#486]
Hi, i search and find somebody said opencl is faster than CUDA,so i want to test! but get this error,can you give me some advance?thks
is opencl included in CUDA 7.5 toolkit?

[zjhxmjl@localhost cpyrit_opencl]$ python setup.py build
The headers required to build the OpenCL-kernel were not found. Trying to continue anyway...
running build
running build_ext
Building modules...
building 'cpyrit._cpyrit_opencl' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c _cpyrit_opencl.c -o build/temp.linux-x86_64-2.7/_cpyrit_opencl.o -Wall -fno-strict-aliasing -DVERSION="0.5.0"
_cpyrit_opencl.c:45:23: fatal error: CL/cl.h: No such file or directory
     #include <CL/cl.h>
                       ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by sbohanan** [comment]
No.  It is not, to the best of my knowledge.  If you're using Debian:

apt-get install linux-headers-$(uname -r)
apt-get install fglrx-driver fglrx-atieventsd fglrx-control fglrx-modules-dkms amd-libopencl1 amd-opencl-dev amd-opencl-icd
aticonfig --initial
reboot

Then try recompiling your pyrit and cpyrit_opencl module.  With Debian, unless you're using a laptop or really old hardware, there's no need to use an outside package.

**Comment by JPaulMora** [comment]
In terms of technology and development, CUDA is way ahead of OpenCl, but sadly for Pyrit the OpenCl module is newer so for now it gives better performance than the CUDA module, note this is a Pyrit only limitation and not a global CL vs CUDA thing.

**Comment by zjhxmjl** [comment]
thanks all,i had solved this problem with install CUDA 7.5 toolkit! finally,i get the result:CUDA is faster than opencl !i used GTX 750TI video card for testing.
