### ISSUE TITLE
Pyrit does not compile on non x86 architecture

### ISSUE THREAD

**Issue by leitao** [JPaulMora/Pyrit#488]
Pyrit is currently broken on non-x86 machines. It does even compile.  This is the problem I am facing when compiling it on non-x86, as ppc64le:

powerpc64le-linux-gnu-gcc: error: unrecognized command line option ‘-maes’
powerpc64le-linux-gnu-gcc: error: unrecognized command line option ‘-mpclmul’

**Comment by JPaulMora** [comment]
Unfortunately I don't have a PPC machine to test this out, if it helps you in any way, I've successfully compiled the main module on ARM devices. I even installed it on my jailbroken iPhone 5s

**Comment by JPaulMora** [comment]
Didn't see your PR when answering, Merged now thanks for supporting Pyrit!

**Comment by leitao** [comment]
Thanks JPaulMora! If you need access to a ppc64 machine, I can provide a instance for you!
