### ISSUE TITLE
Non existing setup.py 

### ISSUE THREAD

**Issue by cnosko** [JPaulMora/Pyrit#495]
I was trying to enable GPU according to your manual, but I don't have a setup.py in /usr/lib/python2.7/dist-packages/cpyrit
When I try to use it, I keep getting "Failed to load Pyrit's OpenCL-core ('Failed to enumerate OpenCL-platforms (Unknown CLresult)" error
APP-SDK is installed, card is R9 270X, Linux Mint Cinnamon 64bit

**Comment by JPaulMora** [comment]
Fixed the ambiguous instruction, the setup.py is located in /modules/cpyrit_opencl/ inside the Pyrit repo.
