### ISSUE TITLE
Progress indicated with attack_passthrough

### ISSUE THREAD

**Issue by gerardbriscoe** [JPaulMora/Pyrit#498]
I needed to know the current password being tested, so that I could use it in a resumable manner without cowpatty. It increases the hash rate by 60%. The output is now as follows:

Tried 3352447614 PMKs so far; 114117 PMKs per second; fupfzczj

How can I got about getting such a change included?

**Comment by JPaulMora** [comment]
This looks really cool, might as well add it globally.

**Comment by gerardbriscoe** [comment]
Great, I will make a pull request then.

**Comment by JPaulMora** [comment]
Awesome!
