### ISSUE TITLE
Cpyrit: nvcc fatal   : Unknown option '-host-compilation'

### ISSUE THREAD

**Issue by Infinitynill** [JPaulMora/Pyrit#507]
Pyrit seemed to install correctly but when I try to install Cpyrit it throws this error with both build and install. I've already installed my Nvidia drivers. I am using the dev toolkit. Honestly can't figure this out. I used Pastebin to keep this clean.

http://pastebin.com/YXciUaW6

**Comment by JPaulMora** [comment]
Hello, it looks you're using pyrit 0.4.0, please download newer source code from git.

**Comment by Infinitynill** [comment]
Alright how can I remove the old installation, and also install cpyrit I need my gpu working with it?

**Comment by JPaulMora** [comment]
just run the new one, files will be overwritten

**Comment by Infinitynill** [comment]
Alright the old one you had to build the cpyrit also. Is that true? What do I need to do to get the GPU recognized? Thank you for your help.

**Comment by JPaulMora** [comment]
what OS are you in?

**Comment by Infinitynill** [comment]
Nevermind I've figured it out. I found the module directory, installed. Then I found the config and enabled cuda. 

~ Thank you so much.

**Comment by Infinitynill** [comment]
I didn't realize their was a newer version for Pyrit. This is a lot easier than the old way.

**Comment by JPaulMora** [comment]
No problem! glad to hear it worked out.
