### ISSUE TITLE
TypeError: use object.new()

### ISSUE THREAD

**Issue by theobch** [JPaulMora/Pyrit#508]
Hi,

I just tried pyrit-0.4.0 (from Google code) et Pyrit from this github, and I'm facing an issue: when I try to launch pyrit, [this error pops out](http://hastebin.com/pikiracili.sql).
I'm using a Dell Precision 7510 with:
* RAM : 16Gb;
* GPU : Nvidia Quadro M2000M (PCIe/SSE2)
* CPU : i7 6920HQ

I followed [BlackMoreOps tutorial](https://www.blackmoreops.com/2014/03/13/install-proprietary-nvidia-driver-kali-linux/ ) to install Nvidia drivers, and everything is working like the tutorial, except pyrit.
Maybe someone could helps me ?
Thanks !

**Comment by ark02** [comment]
Wanted to confirm that I am now having the same issue after an upgrade/dist-upgrade, cannot run any pyrit commands

**Comment by AIIX** [comment]
Can confirm the same on new Kali Install 2016.2. Same Error as above cannot list_cores.

**Comment by ark02** [comment]
Managed to get a different error by following instructions on this page to build and install openCL module
https://github.com/JPaulMora/Pyrit/wiki/GPU-Acceleration

**Comment by ptrakk** [comment]
can't benchmark nor list cores.

**Comment by ptrakk** [comment]
/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py
line 132:
class CPUCore(Core, _cpyrit_cpu.CPUDevice):

line 138:
_cpyrit_cpu.CPUDevice.__init__(self)


appearantly these aren't safe

**Comment by ark02** [comment]
I read somewhere that before python 2.7 __new__ would ignore args, but as of 2.7+ this is no longer true, and new() shouldn't be called with args. 

Not sure if related

**Comment by JPaulMora** [comment]
Will be looking into this, thanks all for your feedback

**Comment by bacondropped** [comment]
Does this help?
```patch
diff --git a/cpyrit/cpyrit.py b/cpyrit/cpyrit.py
index b161006..b060bb7 100644
--- a/cpyrit/cpyrit.py
+++ b/cpyrit/cpyrit.py
@@ -460,7 +460,7 @@ class CPyrit(object):
 
         # CPUs
         for i in xrange(util.ncpus):
-            self.cores.append(CPUCore(queue=self))
+            self.cores.append(CPUCore(self))
 
 
         # Network

```

Apply directly to ~forehead~ `/usr/lib/python2.7/*-packages/cpyrit/cpyrit.py`, or to the same file in the repository (clone, apply, `pip install .`).

**Comment by JPaulMora** [comment]
Hey @theobch and everyone, could you please try if the error persists in Master & Dev branches? thanks.

**Comment by theobch** [comment]
Hi @JPaulMora 
My Kali Linux installation is actually dead, I'll try to test ASAP !

**Comment by JPaulMora** [comment]
Thanks, no the GPU not being detected (NVIDIA) is a separate bug. At least is not a Python error.

**Comment by theobch** [comment]
Alright, glad I could help you !
