### ISSUE TITLE
pyrit benchmark_long Creates Segfaults

### ISSUE THREAD

**Issue by RFKiller** [JPaulMora/Pyrit#522]
I am using the latest version of Pyrit 0.5.1 (with CUDA) from git on Arch Linux, Linux 4.9.11
Before today, Pyrit has run flawlessly with and without CUDA enabled. I have already used Pyrit to crack a couple handshakes, so I know it works fine. And there has been not a single error message during building, installing, and running. So I was curious what my benchmark was when using CUDA since I had previously only ran a benchmark before enabling CUDA in ~/.pyrit/config

After that I was curious how much different the "benchmark" and "benchmark_long" speeds would be. The initial test of
```
[root@archlinux ~]# pyrit benchmark
```
went just fine. In fact, it looked more like this:
```
[root@archlinux ~]# pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (12757.4 PMKs/s)... \ 

Computed 12757.37 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 333.4 PMKs/s (RTT 3.0)
#2: 'CPU-Core (SSE2/AES)': 351.7 PMKs/s (RTT 3.1)
#3: 'CPU-Core (SSE2/AES)': 361.8 PMKs/s (RTT 3.0)
#4: 'CPU-Core (SSE2/AES)': 369.3 PMKs/s (RTT 2.9)
CUDA:
#1: 'CUDA-Device #1 'GeForce GT 730M'': 12518.7 PMKs/s (RTT 2.8)
[root@archlinux ~]#
```
Things are looking great. Everything is working. Etcetera. Until "benchmark_long" which presented me with this glorious little segfault:
```
[root@archlinux ~]# pyrit benchmark_long
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (13244.6 PMKs/s)... \ Segmentation fault (core dumped)
[root@archlinux ~]#
```

**Comment by JPaulMora** [comment]
well thats weird, if you look into Pyrit's code you can see the only difference between benchmark & benchmark_long is the time in seconds. perhaps there's something else going on? could you try cracking a handshake and see how that goes?

by the way, thanks for supporting people around here :3

**Comment by RFKiller** [comment]
@JPaulMora - I don't think it has anything to do with the length of time it was running. I only say that because the 2nd "pyrit benchmark_long" segfaulted before the 1st "pyrit benchmark" would have even completed. It took about 30 seconds to 1 minute before "benchmark_long" segfaulted.

I'll crack one of the handshakes for one of the PCAP dump files you provide with Pyrit, using darkc0de.txt as my password list (though most aren't WPA/WPA2 compliant passwds). I assume we're not actually looking for the password, but just verifying it works without segfaulting, amirite?

**Comment by RFKiller** [comment]
And here is the result of trying to crack a handshake:
```
[root@archlinux ~]# pyrit -i /usr/wordlists/darkc0de.txt -r wpa2psk-2WIRE972.dump attack_passthrough
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing file 'wpa2psk-2WIRE972.dump' (1/1)...
Parsed 568 packets (568 802.11-packets), got 9 AP(s)

Picked AccessPoint 00:40:10:20:00:03 ('2WIRE972') automatically.
Tried 993846 PMKs so far; 15101 PMKs per second. well-stressedte412

Password was not found.

[root@archlinux ~]#
```
So it didn't fail. Well, I mean, it failed because of the dictionary I chose. But it didn't crash or segfault either. So I'm not sure why it would segfault on "benchmark_long" before it would have even finished a regular "pyrit benchmark" had they been running concurrently.

**Comment by RFKiller** [comment]
@JPaulMora - I've run [code]pyrit benchmark_long[/code] a few more times over the past week, and it seems to be working just fine. The issue could have been something else I was doing at the same time that pulled resources from Pyrit, or maybe a mis-typed command or even properly typed command which sent a SIGSEGV command to processes started by my user. I'm not entirely sure, but the problem seems to have solved itself, whatever it was.

Thanks for the help. Closing.

**Comment by JPaulMora** [comment]
Thats great to hear.
