### ISSUE TITLE
can't uninstall v.0.5.0 Ubuntu 14.04.5

### ISSUE THREAD

**Issue by el-soleare** [JPaulMora/Pyrit#523]
I had pyrit / cuda pyrit v.0.4.0 running well, but pyrit v.0.5.0 cannot find cuda gpu !
Also tried Troubleshooting page >> python -c 'from cpyrit import _cpyrit_cuda'
Tried editing ~/pyrit/.config file as suggested. Without OCL enabled I get this :-1: 
````
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 441, in __init__
    CUDA =  cpyrit_cuda.listDevices()
NameError: global name 'cpyrit_cuda' is not defined
````
When I enable it I get cpu's, but no cuda-gpu.
I can't even apt-get remove / purge to remove v.0.5.0  & reinstall v040.
Complete "noob" ubuntu 14.04.5 removal instructions please. Would like to start again with v.040
Any help appreciated.

**Comment by JPaulMora** [comment]
just remove anything called "pyrit" or "cypriot" from `/usr/local/lib/python2.7/dist-packages/` and reinstall from apt.

**Comment by el-soleare** [comment]
Thanks for the quick response. 
I also had to edit out the cuda & ocl entries in  /Home/.pyrit/config file.
Worked great !
Cheers.
