### ISSUE TITLE
What should i do?

### ISSUE THREAD

**Issue by Chir00** [JPaulMora/Pyrit#525]
````
root@Chir0:~/cpyrit-cuda-0.4.0# python2 setup.py build
The CUDA compiler and headers required to build kernel were not found. Trying to continue anyway...
svn: E155007: '/root/cpyrit-cuda-0.4.0' is not a working copy
running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.44...
Executing 'nvcc -m64 --host-compilation C -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc fatal   : Unknown option '-host-compilation'
Traceback (most recent call last):
  File "setup.py", line 175, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 100, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'nvcc -m64 --host-compilation C -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1
````
i already install pyrit and its work but i need pyrit to work with my GPU please help
Thx :)

**Comment by luizbossoi** [comment]
Hello

I see you have issues with cpyrit at " Unknown option '-host-compilation' "
Check my thread please, https://github.com/JPaulMora/Pyrit/issues/524

You should be able to fix your issue by following my steps.

Thanks

**Comment by Chir00** [comment]
There's a important thing here. Edit setup.py file and change the following
nvcc_cmd = NVCC + bit_flag + ' --host-compilation C'
to
nvcc_cmd = NVCC + bit_flag + ' -ccbin clang-3.8 '\

I follow your step and now it works

root@Chir0:~# pyrit list_cores
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

The following cores seem available...
#1:  'CUDA-Device #1 'GeForce GT 730''
#2:  'CPU-Core (SSE2)'
#3:  'CPU-Core (SSE2)'
#4:  'CPU-Core (SSE2)'

Thx :)

**Comment by JPaulMora** [comment]
thats great, what OS are you using?

**Comment by Chir00** [comment]
@JPaulMora Hi boss
Kali Linux 64bit
:)

**Comment by JPaulMora** [comment]
Nice!

**Comment by JPaulMora** [comment]
Hey @Chir00, I submitted a fix for this issue not so long ago. Could you tell me if it fixes your error too?  just `cd` into your Pyrit dir and `git pull` and try to compile (don't need to install) pyrit-cuda. I'll appreciate your input.

**Comment by Chir00** [comment]
@JPaulMora Sure why not?
if it can help i will do it for you boss.
but i will ask you something.
you mean i need to remove pyrit-cuda before git pull and compile new one right?

**Comment by Chir00** [comment]
@JPaulMora  i'm remove all old pyrit and use git clone.
so this is all (i think i do it right xD)
root@Chir0:~/Pyrit# git pull
Already up-to-date.
root@Chir0:~/Pyrit# pyrit list_cores
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

The following cores seem available...
#1:  'CPU-Core (SSE2/AES)'
#2:  'CPU-Core (SSE2/AES)'
#3:  'CPU-Core (SSE2/AES)'
#4:  'CPU-Core (SSE2/AES)'
root@Chir0:~/Pyrit# cd modules
root@Chir0:~/Pyrit/modules# ls
cpyrit_calpp  cpyrit_cuda  cpyrit_opencl
root@Chir0:~/Pyrit/modules# cd cpyrit_cuda
root@Chir0:~/Pyrit/modules/cpyrit_cuda# ls
COPYING  _cpyrit_cuda.c  _cpyrit_cuda.h  _cpyrit_cudakernel.cu  MANIFEST.in  setup.py
root@Chir0:~/Pyrit/modules/cpyrit_cuda# python setup.py build
The CUDA compiler and headers required to build kernel were not found. Trying to continue anyway...
running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.44...
Executing 'nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Building modules...
building 'cpyrit._cpyrit_cuda' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c _cpyrit_cuda.c -o build/temp.linux-x86_64-2.7/_cpyrit_cuda.o -Wall -fno-strict-aliasing -DVERSION="0.5.0"
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/cpyrit
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/_cpyrit_cuda.o -lcrypto -lcuda -lz -o build/lib.linux-x86_64-2.7/cpyrit/_cpyrit_cuda.so
root@Chir0:~/Pyrit/modules/cpyrit_cuda# pyrit list_cores
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

The following cores seem available...
#1:  'CPU-Core (SSE2/AES)'
#2:  'CPU-Core (SSE2/AES)'
#3:  'CPU-Core (SSE2/AES)'
#4:  'CPU-Core (SSE2/AES)'
root@Chir0:~/Pyrit/modules/cpyrit_cuda# 

pyrit 0.5.1 work fine but cpyrit didn't work
hope i do it right :/

**Comment by JPaulMora** [comment]
alright, thanks. You did fine except I think you forgot to install (reinstall?) the cuda-toolkit (`The CUDA compiler and headers required to build kernel were not found.`)

**Comment by Chir00** [comment]
@JPaulMora  nvm boss thx for your help and @luizbossoi too.

See you later :)
