### ISSUE TITLE
cpyrit/_cpyrit_cpu.c:35:10: fatal error: 'openssl/hmac.h' file not found

### ISSUE THREAD

**Issue by ttb44** [JPaulMora/Pyrit#527]
Trying to compile pyrit on mac os 10.12.4.  Getting cpyrit/_cpyrit_cpu.c:35:10: fatal error: 'openssl/hmac.h' file not found.

Tried to follow instructions [here](https://github.com/JPaulMora/Pyrit/issues/513) without success.  

```
git clone https://github.com/JPaulMora/Pyrit.git
sudo -H pip install psycopg2
sudo -H pip install scapy==2.3.2    **FAILS**
sudo -H pip install pcapy                 **FAILS**
cd Pyrit
python setup.py clean
python setup.py build                      **FAILS**
sudo python setup.py install
```
Any help much appreciated.  Thanks

````
s/2.7/share': Operation not permitted
  
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-BFCx0S/scapy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lLZJIY-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-BFCx0S/scapy/
````

**Comment by ttb44** [comment]
Okay, [this](https://github.com/servo/servo/issues/15293) got me past the hmac.h error..

> sudo ln -s /usr/local/opt/openssl/include/openssl /usr/local/include/openssl
> sudo ln -s /usr/local/opt/openssl/lib/* /usr/local/lib/

**Comment by ttb44** [comment]
Arggh, got it to compile, gpu not listed..

> DasFljk:bin patrickcooney$ pyrit list_cores
> Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
> https://github.com/JPaulMora/Pyrit
> This code is distributed under the GNU General Public License v3+
> 
> The following cores seem available...
> #1:  'CPU-Core (SSE2/AES)'
> #2:  'CPU-Core (SSE2/AES)'
> #3:  'CPU-Core (SSE2/AES)'
> #4:  'CPU-Core (SSE2/AES)'

I've got a ..

> Intel Iris Graphics 6100:
> 
>   Chipset Model:	Intel Iris Graphics 6100
>   Type:	GPU

**Comment by RFKiller** [comment]
Please close this. This is not a forum for general questions. This is for issues and bugs regarding Pyrit, not help for individual graphics cards. Install the OpenCL version of Pyrit if you can. You won't be able to use CUDA. Now, your original "issue" was already solved when you realized you needed to install openssl - so please close this.

**Comment by ttb44** [comment]
I wasn't aware that there was an OpenCL version of Pyrit, isn't this controlled by the variables in the config file, per the [wiki](https://github.com/JPaulMora/Pyrit/wiki/GPU-Acceleration)?

**Comment by RFKiller** [comment]
You can enable or disable CUDA or OpenCL during the build process by editing setup.py which just sets the defaults for the ~/.pyrit/config file. Most people don't edit the setup.py and just edit the pyrit config file instead. But enabling the options in the config file will do nothing if you didn't build the OpenCL or CUDA module for Pyrit.

**Comment by ttb44** [comment]
It's not clear to me how to edit setup.py in order to build the OpenCL version.  Is this documented somewhere?

**Comment by ttb44** [comment]
nevermind, i got it.  thanks for the help.  closing..

**Comment by RFKiller** [comment]
Editing the setup file just enables/disables the options by default in the config file. Again, these options mean nothing if you don't build the OpenCL module for Pyrit. And yes, there is plenty of documentation on how to build the OpenCL module. So please stop using this as a personal forum. Google search, look through the documentation here, or search the Kali forums.

**Comment by JPaulMora** [comment]
Hello! 

Pyrit supports the latest scapy (2.3.3) so doing `sudo pip install scapy` should work. 

about openssl, macOS no longer ships with these libraries so you have to install them using [Brew](https://brew.sh) `brew install openssl` and link them like you did `sudo ln -s /usr/local/opt/openssl/lib/* /usr/local/lib/` that should be it though.

**Comment by pradeepdamera** [comment]
ttb44 
how did you solve this issue?
cpyrit/_cpyrit_cpu.c:35:10: fatal error: 'openssl/hmac.h' file not found

**Comment by faizi021** [comment]
Even im stuck since a month..cannot install pyrit....im new in kali...plz helppppp

**Comment by uhum98** [comment]
sudo apt-get install openssl-dev

**Comment by uhum98** [comment]
if you find fatal error pcap.h  tap:
sudo apt-get install libpcap-dev

**Comment by faizi021** [comment]
Thanks

**Comment by faizi021** [comment]
Will check

**Comment by uhum98** [comment]
worked ?

**Comment by tejas15802** [comment]
> worked ?

No, it did not.. I mean this `sudo apt-get install openssl-dev` or `sudo apt-get install openssl-devel` or `sudo apt-get install openssl openssl-dev` none seems to be present in debian repos

**Comment by devilkkw** [comment]
> > worked ?
> 
> No, it did not.. I mean this `sudo apt-get install openssl-dev` or `sudo apt-get install openssl-devel` or `sudo apt-get install openssl openssl-dev` none seems to be present in debian repos

use `sudo apt-get install libssl-dev`

**Comment by ivanotyt** [comment]
im having the same problem.
i tried everything yall suggested, nothing worked:
the error is `E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`
also tried `run apt-get update` and the other thing, the second didnt work at all
pls help(?)
