### ISSUE TITLE
Can bumblebee work with pyrit?

### ISSUE THREAD

**Issue by G-lost** [JPaulMora/Pyrit#530]
I had installed bumblebee. And now I found CUDA can not work.
```
# optirun pyrit list_cores
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

The following cores seem available...
#1:  'CPU-Core (SSE2/AES)'
#2:  'CPU-Core (SSE2/AES)'
#3:  'CPU-Core (SSE2/AES)'
#4:  'CPU-Core (SSE2/AES)'
```

CUDA core did not show up

and here is my config
```
default_storage = file://
limit_ncpus = 0
rpc_announce = true
rpc_announce_broadcast = false
rpc_knownclients = 
rpc_server = false
use_CUDA = true
use_OpenCL = false
workunit_size = 75000
```

and here is benchmark
```
# optirun pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (2019.0 PMKs/s)... - 

Computed 2019.02 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 556.3 PMKs/s (RTT 3.0)
#2: 'CPU-Core (SSE2/AES)': 563.5 PMKs/s (RTT 3.1)
#3: 'CPU-Core (SSE2/AES)': 564.3 PMKs/s (RTT 3.1)
#4: 'CPU-Core (SSE2/AES)': 554.6 PMKs/s (RTT 3.0)
CUDA:
```

can anyone help me, I'm new to Kali and Linux, if you need more information I will put them up

**Comment by JPaulMora** [comment]
Hello! Did CUDA worked prior bumblebee install?

**Comment by G-lost** [comment]
I didn't try to use CUDA before I install bumblebee. So I'm not sure.

This is what I found.
Bumblebee - Arch Wiki
https://wiki.archlinux.org/index.php/bumblebee

> ### CUDA without Bumblebee

>You can use CUDA without bumblebee. All you need to do is ensure that the nvidia card is on:
>```
> # tee /proc/acpi/bbswitch <<< ON
>```
>Now when you start a CUDA application it is going to automatically load all the necessary modules.
>To turn off the nvidia card after using CUDA do:
>```
> # rmmod nvidia_uvm
> # rmmod nvidia
> # tee /proc/acpi/bbswitch <<< OFF
>```

I have tried this but didn't work either.
Maybe I should uninstall bumblebee? @JPaulMora

**Comment by G-lost** [comment]
Well I solved this problem today. Because the bumblebee install the Nvidia driver in somewhere else. So I change the setup.py and it worked!
But there is another problem. When I begin to crack password pyrit can't read the .cap file why?
'''
~# pyrit -r test-01.cap analyze
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing file 'test-01.cap' (1/1)...
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 467, in analyze
    parser = self._getParser(capturefile)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 183, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 28 captured bytes, only got 0
'''
Can anyone help? Thank you.

**Comment by G-lost** [comment]
Ok, I got this. I found a post that solved this problem.

> Anonymous - 2010-09-30  
>Originally posted by: lukas.l...@gmail.com
>The file is in fact corrupted and the error you posted comes directly from libpcap. Pyrit is just very disgraceful >about that ... :-/
>Open the file in Wireshark, notice the error message any save everything to a new file. Be sure to check >"save displayed packets". Wireshark creates a new dump that includes everything to the point where the file >is cut off. Use Pyrit on the new file.
>Another way is to use Pyrit's "stripLive" command such as 'pyrit -r test-capture.cap -o new_file.cap stripLive'. >Pyrit will read the packets one by one and write a new dump file with every 'useful' packet it can find until you >get the same error as above. The new file is just a few kilobytes and includes everything you need.
>Status: Invalid
So, I used this code:
```
# pyrit -r test-01.cap -o newTest.cap stripLive
```
and it worked, I got the right password.
