### ISSUE TITLE
Hi JPaulMora, is posible use pyrit for crack md5 rar zip password?

### ISSUE THREAD

**Issue by reproteq** [JPaulMora/Pyrit#533]
Hi JPaulMora, is posible use pyrit for crack md5 rar zip password?
Is posible implemented pyrit cuda gpu for cracking password rar and zip ?

thanks alot man.

**Comment by JPaulMora** [comment]
Hi, it is definitely possible but it wouldn't be too useful as every single zip file would need gigantic amounts of space. You would be better of using [Hashcat](https://hashcat.net/hashcat/) or [John the Ripper](http://www.openwall.com/john/) (jumbo version recommended).

**Comment by reproteq** [comment]
Ok, Paul thanks i go test john the ripper jumbo .
have nice day man.
