### ISSUE TITLE
pcap.h is missing, causes fatal error during install

### ISSUE THREAD

**Issue by RickMakesStuff** [JPaulMora/Pyrit#536]
when installing the main Pyrit module, I see this error message:
"running install
running build
running build_py
running build_ext
building 'cpyrit._cpyrit_cpu' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cpyrit/_cpyrit_cpu.c -o build/temp.linux-x86_64-2.7/cpyrit/_cpyrit_cpu.o -Wall -fno-strict-aliasing -DVERSION="0.5.0" -maes -mpclmul
cpyrit/_cpyrit_cpu.c:40:18: **fatal error: pcap.h: No such file or directory**
compilation terminated.
Failed to build; Compiling without AES-NI
building 'cpyrit._cpyrit_cpu' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cpyrit/_cpyrit_cpu.c -o build/temp.linux-x86_64-2.7/cpyrit/_cpyrit_cpu.o -Wall -fno-strict-aliasing -DVERSION="0.5.0"
cpyrit/_cpyrit_cpu.c:40:18: **fatal error: pcap.h: No such file or directory**
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1"

The CUDA module works fine, but this error is persistent through 3 versions I have tried.

**Comment by JPaulMora** [comment]
Hi, you need to install libpcap.

**Comment by RickMakesStuff** [comment]
I am in Ubuntu Tegra (ARM-64). The board is a Jetson TX1. I tried Hashcat on it, but that is not working. Im trying Pyrit, but not having much luck either.

**Comment by Manojkumar132006** [comment]
> Hi, you need to install libpcap.
> 
> EDIT: What OS are you in? I may be I could guide you further with that info.

do we need to use *apt install libpcap* ?
