### ISSUE TITLE
OpenCL not working

### ISSUE THREAD

**Issue by SmallSharky** [JPaulMora/Pyrit#538]
I see this response when writing "use_OpenCL=true" to config:

```
>$ pyrit list_cores
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 295, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/lib/python2.7/site-packages/cpyrit/cpyrit.py", line 451, in __init__
    dev = _cpyrit_opencl.OpenCLDevice(platform_idx, dev_idx)
SystemError: Failed to get device-name (CL_INVALID_VALUE)
```

I was installed all necessary packages, successfully tested pyopencl, but pyrit not working..
Have you any ideas? 

About PC:
Archlinux, x86-64, 
GPUs:
AMD Radeon (TM) R7 M340 (AMD ICELAND / DRM 3.15.0 / 4.12.13-1-ARCH, LLVM 5.0.0)
AMD Radeon R7 Graphics (AMD CARRIZO / DRM 3.15.0 / 4.12.13-1-ARCH, LLVM 5.0.0)
Platform version: OpenCL 1.1 Mesa 17.2.1

**Comment by JPaulMora** [comment]
I recently installed arch, will test there.

**Comment by SmallSharky** [comment]
At this time all is OK. I just installed amdgpu-pro opencl driver. Pyrit works fine with it. But in the mesa case it isn't working.

**Comment by jvesely** [comment]
The mesa case should be fixed by https://github.com/JPaulMora/Pyrit/pull/572

**Comment by JPaulMora** [comment]
Ok
