### ISSUE TITLE
How to Install Pyrit Cuda + Toolkit 8 + Nvidia GTX 1060 in Kali Linux 2017.3

### ISSUE THREAD

**Issue by Hackitfree** [JPaulMora/Pyrit#553]
Guide -How To Install Pyrit Cuda + Toolkit 8 + Nvidia Gtx 1060 In Kali Linux 2017.3

****Clean Install Kali 2017.3 Kernel 4.13.0-Kali1-Amd64 And Update
*Add This Line To /Etc/Apt/Sources.List*

deb http://http.kali.org/kali kali-rolling main contrib non-free

****add key*

wget -q -O - https://archive.kali.org/archive-key.asc  | apt-key add 

****update*

apt update && apt upgrade && apt dist-upgrade

apt autoremove

apt remove pyrit

echo -e "blacklist nouveau\noptions nouveau modeset=0\nalias nouveau off" > /etc/modprobe.d/blacklist-nouveau.conf

update-initramfs -u && reboot

*After the reboot-verify that nouveau is disabled

lsmod | grep -i nouveau

****must be a blank return

apt install nvidia-driver ocl-icd-libopencl1 nvidia-cuda-toolkit

apt install python2.7-dev python-pycuda-doc python-pycuda python3-pycuda mesa-utils libgl1-nvidia-glx 

apt install libssl-dev zlib1g-dev libpcap-dev nvidia-xconfig

reboot

*********Pyrit prep

git clone https://github.com/JPaulMora/Pyrit.git

gedit /root/.bashrc

*Add these lines to the end of .bashrc

PATH=$PATH:/usr/lib/nvidia-cuda-toolkit/bin.
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-cuda-toolkit/lib:/lib
export PATH
export LD_LIBRARY_PATH 

*Pyrit_Cuda Prep and Install

cd /root/Pyrit/modules/cpyrit_cuda/

gedit setup.py

Edit the setup.py, line 34,edit it from*

for path in ('/usr/local/cuda', '/opt/cuda'):

*to:

for path in ('/usr/local/cuda','/usr/lib/nvidia-cuda-toolkit','/opt/cuda'):

*line 88,edit it from**

nvcc_cmd = NVCC+ bit_flag + ' -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'

*to:

nvcc_cmd = NVCC + bit_flag + ' -ccbin clang-3.8 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'

*then

cd /root/Pyrit/modules/cpyrit_cuda

*and install

python setup.py clean build install

cd /root/Pyrit/

python setup.py clean build install

*yes 2 times in differnt dir*
*last thing

gedit /root/.pyrit/config

*change from:

use_CUDA = false

*to

use_CUDA = true

*now check your GPU

pyrit list_cores

ENJOY !!!

*Note: GPU works best with 1 CPU core
gedit /root/.pyrit/config
*set:
limit_ncpus = 1

My score:

root@kali:/# pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (123359.7 PMKs/s)... | 

Computed 123359.69 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 1195.8 PMKs/s (RTT 2.9)
CUDA:
#1: 'CUDA-Device #1 'GeForce GTX 1060 3GB'': 133063.0 PMKs/s (RTT 1.0)

**for powermizer and manual fan control**
nvidia-xconfig --cool-bits=12
reboot

**Comment by Hackitfree** [comment]
If you wanna install Pyrit properly then follow my guide Good luck 👍

**Comment by jTimas** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    self.CUDAs.append(CUDACore(queue=self, dev_idx=dev_idx))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 243, in __init__
    _cpyrit_cuda.CUDADevice.__init__(self, dev_idx)
SystemError: Unknown CUresult.

I get this error, when I do pyrit list_cores


```

**Comment by Hackitfree** [comment]
Hi JTimas !  
Did you follow all the process or just few lines? I would be surprised if you did clean install and then got that-coz i tried this process from start to end with no mistakes..Please answer -i would be happy to help you..Anyway check hashcat if it works with your card-and if so-then reinstall Pyrit from source-(not just install) but (BUILD MAKE INSTALL) from SOURCE files...(Doesnt work if you dont compile it yourself)

**Comment by jTimas** [comment]
Hi, I did it step by step. How to check hashcat compatibility with my card?

**Comment by Hackitfree** [comment]
Well I wanted to help community by writing this thread and after 1 guy succeded and thanked me -i wanna make sure i help you too.
First -for Hashcat test use this command 
hashcat -b  - and to specify which device to use use -D and number of device...For example i have AMD Ryzen processor 6 cores 12 therads and Nvidia GTX 1060 card...This commands explain it all i believe :
root@kali:~# hashcat -D 1 -b
hashcat (pull/1273/head) starting in benchmark mode...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1060 3GB, skipped.

OpenCL Platform #2: The pocl project
====================================
* Device #2: pthread-AMD Ryzen 5 1600 Six-Core Processor, 18106/18106 MB allocatable, 12MCU

Hashtype: MD4

Speed.Dev.#2.....:   232.5 MH/s (54.02ms)

Hashtype: MD5

Speed.Dev.#2.....:   157.4 MH/s (79.89ms)

Hashtype: Half MD5

Speed.Dev.#2.....: 93742.8 kH/s (67.06ms)

Hashtype: SHA1

^C
root@kali:~# hashcat -D 2 -b
hashcat (pull/1273/head) starting in benchmark mode...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1060 3GB, 752/3010 MB allocatable, 9MCU

OpenCL Platform #2: The pocl project
====================================
* Device #2: pthread-AMD Ryzen 5 1600 Six-Core Processor, skipped.

Hashtype: MD4

Speed.Dev.#1.....: 17487.4 MH/s (69.03ms)

Hashtype: MD5

Speed.Dev.#1.....: 10086.2 MH/s (59.85ms)

Hashtype: Half MD5

Speed.Dev.#1.....:  6742.0 MH/s (89.53ms)

Hashtype: SHA1

see the speed improvement? OK now the matter of installing Pyrit...I deliberately deleted my last Kali install and started again just to check step by step if i wrote the instructions right..I came to place just before  "*Pyrit prep" and as you can see my Cuda and Nvidia driver are sucessfully installed and work with Hashcat (last 2 hashcat commands i printed out" (sorry if my English is bit bad and rusty I hope you can follow me)..I am continuing to install and follow the guide and in an hour you will get my output..Peace out for now :)

**Comment by Hackitfree** [comment]
Also i suggest to learn more about "nvidia-smi" command and use it as needed with your videocard-for example "nvidia-smi -pl 65" -my favorite command with which i can limit the power drawn by my card(-pl) POWERLIMIT -I use 65 so the power drawn never excede 95W (isnt exact science i know :)) - then you can open new terminal window  and use "nvidia-smi dmon" so you can monitor all kind of temp -powerdraw ETC..Use also "nvidia-settings" for graphical settings of your video card...(read something about this command so you can change your fan-speed and coreclock)

**Comment by Hackitfree** [comment]
Also i suggest to learn more about "nvidia-smi" command and use it as needed with your videocard-for example "nvidia-smi -pl 65" -my favorite command with which i can limit the power drawn by my card(-pl) POWERLIMIT -I use 65 so the power drawn never excede 95W (isnt exact science i know :)) - then you can open new terminal window  and use "nvidia-smi dmon" so you can monitor all kind of temp -powerdraw ETC..Use also "nvidia-settings" for graphical settings of your video card...(read something about this command so you can change your fan-speed and coreclock)

**Comment by Hackitfree** [comment]
Unfortunately my Pyrit install didn't work too..I messed up with copying commands or something or the new Kali-updates messed up something with the Python2.7 ..Anyway i fixed it by:

apt update && apt upgrade && apt autoremove && apt -f install && apt upgrade
cd /root//Pyrit/modules/cpyrit_cuda

*make sure your file setup.py is being changed accordingly(line 34and 88)
*then rebuild cuda_pyrit by command: 

python setup.py clean build install
*here is my output:

root@kali:~/Pyrit/modules/cpyrit_cuda# python setup.py clean build install
running clean
Removing temporary files and pre-built GPU-kernels...
running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.61...
Executing '/usr/lib/nvidia-cuda-toolkit/bin/nvcc -m64 -ccbin clang-3.8 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Building modules...
running install
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/cpyrit_cuda-0.5.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/cpyrit_cuda-0.5.0.egg-info
*Please tell me what you did -and i hope it worked finnaly :)

**Comment by jTimas** [comment]
I reinstalled different linux distros and it went wrong somewhere. I'm tired of it. In a few days I'll try on clean kali linux again and will write here. By the way, do you have one graphic card or two? Because my laptop might have Optimus technology and I think that is the reason why it is not working

**Comment by Hackitfree** [comment]
You can find similar install-guide in issues-thread under "How to Install Pyrit Cuda + Toolkit 8 + Nvidia GTX 1070 in Kali Linux 2017.1" and they explain optimus too-(so switching from nvidia to intel GPU) 
Well i tried all the perks in Pyrit and find that Hashcat is much reacher in options and same or faster in speed..So stick to Hashcat coz all you need for it to work is NVIDIA-cuda and its damn easy to install (apt install nvidia-cuda)
Wish you best luck cracking hashes :)

**Comment by jTimas** [comment]
Thank you it works fine with hashcat, I think so. I don't know why pyrit doesn't detect my GPU as CUDA device.

**Comment by maelkokta** [comment]
THANK YOU Hackitfree. WORK for me.

root@kali:~# pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (27981.6 PMKs/s)... | 

Computed 27981.60 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 795.3 PMKs/s (RTT 3.0)
CUDA:
#1: 'CUDA-Device #1 'GeForce 930MX'': 29444.9 PMKs/s (RTT 2.8)

**Comment by younerd4ever** [comment]
Dear author, I have stuck on this step:
*and install

python setup.py clean build install

It is error:python setup.py clean build install
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    import zlib
ImportError: No module named zlib
 

i tried to remove zlib, but nothing helpful.


Help me please, I don't want to use Ubuntu!!:)

**Comment by younerd4ever** [comment]
and why my GPU is off????

nvidia-smi
Mon Jun 25 14:53:20 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   34C    P8    10W / 120W |    156MiB /  6077MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       514      G   /usr/lib/xorg/Xorg                            14MiB |
|    0       600      G   /usr/bin/gnome-shell                          23MiB |
|    0       840      G   /usr/lib/xorg/Xorg                            60MiB |
|    0       925      G   /usr/bin/gnome-shell                          55MiB |
+-----------------------------------------------------------------------------+

**Comment by younerd4ever** [comment]
0 GeForce GTX 106... Off

**Comment by vido89** [comment]
I also followed instructions but Im getting 

```
pyrit list_coresPyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    self.CUDAs.append(CUDACore(queue=self, dev_idx=dev_idx))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 243, in __init__
    _cpyrit_cuda.CUDADevice.__init__(self, dev_idx)
SystemError: Unknown CUresult.
```
Im using gtx750Ti with driver 384.130 and cuda_10

**Comment by younerd4ever** [comment]
Just don't even try to solve this! I had been tried for 3 month, just change kali on mint. I recommend you to

**Comment by vido89** [comment]
Hi @younerd4ever Iv dowloaded mint but cant compile cpyrit_cuda Im getting an error 
`clang-3.8: No such file or directory`

**Comment by vido89** [comment]
@younerd4ever tnx for suggestion :)

**Comment by vido89** [comment]
Im using ubuntu 16.04 and it does not work but on mint 19 works like charm, and mint is based on 18-04 ? Cheers :)
