### ISSUE TITLE
Pyrit + Gpu Amd RX 580

### ISSUE THREAD

**Issue by ITfirewall** [JPaulMora/Pyrit#569]
@JPaulMora 

Hi everyone,
I have a Sapphire Nitro+ RX 580  8GB.  I have been having problems. 

How can I make the vídeo card work with Pyrit???
What is the right  Amd driver and installation procedures???

I tried to install the gpu in Ubuntu and Kali... and it seems that there is some kind of problem with the Amd driver, because the operating system says there is 4 Gb of memory in gpu instead of 8 Gb memory of my gpu. 
Someone have gpus Amd RX series working with Pyrit??

**Some years ago, I had Backtrack 5 r3 with Pyrit and gpus Amd radeons + amd Catalyst 13.12 and  I never had  any problems.

**Comment by jvesely** [comment]
after https://github.com/JPaulMora/Pyrit/pull/572
I'm able to run Pyrit benchmark on my carrizo GPU using mesa3d/clover
