### ISSUE TITLE
WIFITE WSL2

### ISSUE THREAD

**Issue by tetrazav** [JPaulMora/Pyrit#624]
Talvez isso não seja um problema. Talvez apenas não seja compativel mas vamos la
eu uso o terminal do windows para muitas coisas e agora com o wsl2 parece que tudo ficou ainda mais claro por aqui
porem eu não consigo colocar meu ralink em modo promiscuo, sempre da esse erro no wifite

[+] Checking airmon-ng...
[!] airmon-ng did not find any wireless interfaces
[!] Make sure your wireless device is connected
[!] See http://www.aircrack-ng.org/doku.php?id=airmon-ng for more info

mas eu ja me certifiquei de que o adaptador esta conectado
uso o seguinte comando para listar o adaptador no powershell:

PS C:\Users\h2uro&gt; usbipd wsl list
BUSID DEVICE STATE
1-1 802.11n USB Wireless LAN Card Attached - kali-linux
1-6 Web Camera Not attached
1-7 Qualcomm Atheros QCA9377 Bluetooth Not attached

no texto acima o adaptador já esta conectado ao kali mas se não fosse o caso eu usaria o comando: C:\Users\h2uro&gt; usbipd wsl attach --busid 1-1

e logo em seguda o adaptador estara conectado ao kali no wsl
o problema e que o wifite nao reconece o adaptador
o comando lsusb mostra o segunte:

$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

mas quando executo o wifite o erro:
[+] Checking airmon-ng...
[!] airmon-ng did not find any wireless interfaces
[!] Make sure your wireless device is connected
[!] See http://www.aircrack-ng.org/doku.php?id=airmon-ng for more info

**Comment by xkpx64** [comment]
Sorry to say it bro, but i dont think its possible to use Wifite with WSL2  ( i have also tried, i also even try to recompile the WSL kernel ) but no luck saddly.

**Comment by fgsoftware1** [comment]
wsl dont have bridge access

**Comment by Lasheb** [comment]
fgh

**Comment by kimocoder** [comment]
Hi there, just to be clear... All works in WSL due to WSL USB application that can bind and unbind USB devices in WSL, :+1: 

So, he's perfectly correct :1st_place_medal:
