### ISSUE TITLE
Pip install .

### ISSUE THREAD

**Issue by Faveboy** [JPaulMora/Pyrit#652]
note: This error originates from a subprocess, and is likely not a problem with pip.                ERROR: Failed building wheel for pyrit          Failed to build pyrit                             ERROR: Could not build wheels for pyrit, which is required to install pyproject.toml-based projects

Help me to solve my errors

**Comment by JPaulMora** [comment]
Hey @Faveboy you did not provide the error log, I'll be closing this issue
